[package]
name = "console_sine_wave_more"
version = "0.1.0"
edition = "2021"

[dependencies]

sagebox = { path = "../../../sagebox"}     
#sagebox = { path = "../../../sagebox", features = [ "link_dynamic"]  }   # uncomment to link to sagebox.dll 